### ISSUE TITLE
API 似乎將未提供姓名暱稱的文章連帶替除掉了

### ISSUE THREAD

**Issue by shawnlin0201** [hexschool/w3hexschool-API#1]
**時間**：2020/02/18
**問題**：[API](https://raw.githubusercontent.com/hexschool/w3hexschool-API/master/data.json) 內容似乎將沒提供姓名暱稱的參賽文章關閉了？
**行為**：request **正常**且 response **正常**。
**預期**：能節錄到所有且包含未提供姓名綽號的參賽文章。
**結果**：資料來源剩下只有提供有姓名的文章。
**線上**：[website-demo](https://shawnlin0201.github.io/hexschool-2020-challenge-blog-list/)

**Comment by hsiangfeng** [comment]
Hi，shawnlin0201：
你好，我是六角學院的 Ray :D

感謝回報唷~
其實是因為我剛好在調整 API，所以才會導致這個問題發生，一方面是忘記寫參數。

此外也因為我這邊增加一些功能讓這個資料可以全自動化，目前看你製作出來的成品也已經有出現「沒有姓名暱稱的參賽文章」了，所以 API 已經正常囉~

那麼希望以上說明有替你解答，那麼我就關閉該 Issues，如果還有疑問也歡迎再次打開哩 :D
