### ISSUE TITLE
API Null 似乎尚未合併完全

### ISSUE THREAD

**Issue by shawnlin0201** [hexschool/w3hexschool-API#2]
**時間**：2020/02/21
**問題**：[API](https://raw.githubusercontent.com/hexschool/w3hexschool-API/master/data.json) Null 似乎尚未合併完全。
**行為**：request **正常**且 response **正常**，但資料有疑問。
**預期**：不公開的參賽者名稱預設值為 null，並且其資料會統一合併在一起。

### 預期 before
```javascript
{
  blogList: [
      {
        title: "postA",
        url: "...",
      }
    ],
    updateTime: "...",
    blogUrl: "...",
    name: null, // 參賽者 A
},
{
  blogList: [
      {
        title: "postB",
        url: "...",
      },
    ],
    updateTime: "...",
    blogUrl: "...",
    name: null, // 參賽者 A
},
```

### 預期 after
```javascript
{
  blogList: [
      {
        title: "postA",
        url: "...",
      },
      {
        title: "postB",
        url: "...",
      },
    ],
    updateTime: "...",
    blogUrl: "...",
    name: null, // 合併 參賽者 A 與 B 的內容
},
```
**結果**：仍有四筆 null 尚未合併，且**目測**部分名稱欄為 null 值的整筆資料都消失，詳見 [API](https://raw.githubusercontent.com/hexschool/w3hexschool-API/master/data.json) 最後四筆資料。
**線上**：[website-demo](https://shawnlin0201.github.io/hexschool-2020-challenge-blog-list/)
> 註：
> 目前我網站上的版本匿名 null 值將會以 `匿名工程師` 方式呈現

**Comment by shawnlin0201** [comment]
經由討論後確定關於 name 值 `null` 合併方法採用 **email** 辨識
其餘資料因為資料流本身可能都會有異動
e.g. 使用者突然公開 / 關閉了暱稱等等行為，甚至改文章名稱等等行為導致前後天資料比對時異常。
我認為由**發文者使用這些搜尋器如果還找不到自己文章**才來回報這個問題可能會恰當，感謝協助。

**Comment by hsiangfeng** [comment]
Hi，shawnlin0201:
我是六角學院的 Ray :D

沒有錯，該 API 是採用 Email 去比對並整合(但不會公開 Email)，但目前來講因為有許多人只報名，但在開賽後都沒有回報文章，所以這些人就不會出現在 API 中，此外整合的邏輯就跟以下是相同的

```
{
  "blogList": [ // 文章列表
    {
      "title": "PixiJS V5 教學 (0)", // 文章標題
      "url": "https://hsiangfeng.github.io/javascript/20200203/3949702627/" // 文章 URL
    },
    ...
  ],
  "updateTime": "2020/2/18 下午 7:49:36", // 表單更新時間
  "blogUrl": "https://hsiangfeng.github.io/", // 部落格網址
  "name": "Ray" // 若有勾選願意公開暱稱則會顯示暱稱
}
```

只是 name 變成 null，原有的設計會散落出來導致資料結構較亂，所以才做整合，因為每一位使用者的部落格 url(blogUrl) 都會填寫相同位置，所以才會這樣子設計。

以目前來講是已經不會再做任何調整了，除非 API 有出現甚麼怪問題(?!)

那麼就像你說的參賽者有權利隨時可以開關自己的暱稱，所以如果採用前後天比對資料的話是會出現異常的，所以該 API 並不會比對前一天與後一天的資料對比，而是即時性拉取 Google Sheet 資料。
