### ISSUE TITLE
參賽者沒有在 API 名單內

### ISSUE THREAD

**Issue by gonsakon** [hexschool/w3hexschool-API#3]
這裏查了下我的格式看起來沒問題，但我**猜測有可能是我測試時重複報名多次**，所以程式有濾掉？再請幫我查詢看看，3Q~

PS：早上有收到信件，這位參賽者也反應沒有在 API 內，他跟我相同之處也在有重複報名的樣子，因為個資，所以只附上他的[第一篇投稿連結](https://onlystp417.github.io/article/CSS_background_1.html)。

**Comment by hsiangfeng** [comment]
@gonsakon 
表單上看起來看似斷行，但實際是沒有斷行成功
<img width="744" alt="圖片" src="https://user-images.githubusercontent.com/19990752/75130198-f977ff80-5707-11ea-8ef0-f637b61cf30a.png">

所以才會導致資料沒出來
<img width="347" alt="圖片" src="https://user-images.githubusercontent.com/19990752/75130114-97b79580-5707-11ea-8fa5-4879543f5803.png">

而同學的部落格網址表單
<img width="729" alt="圖片" src="https://user-images.githubusercontent.com/19990752/75130224-16143780-5708-11ea-9913-2cb8389f0a98.png">

這個問題在於他的部落格網址沒有完整正確的填入所導致
<img width="475" alt="圖片" src="https://user-images.githubusercontent.com/19990752/75130135-af8f1980-5707-11ea-88a4-27030f1387a0.png">

只要修正以後就可以解決囉（我這邊不能調整，要由原使用者調整，否則表單會錯亂)。
