### ISSUE TITLE
參賽者沒有在 API 名單內

### ISSUE THREAD

**Issue by dogwantfly** [hexschool/w3hexschool-API#4]
我也沒有出現在 API 名單內，目前檢查格式應該沒錯，不知道有沒有沒發現的錯誤，這是我填的[部落格連結](https://medium.com/@tina2793778)，感謝！

**Comment by hsiangfeng** [comment]
Hi，dogwantfly：
你好，我是六角學院的 Ray :D

格式是有錯誤的唷~~
所以再麻煩您調整一下

<img width="842" alt="圖片" src="https://user-images.githubusercontent.com/19990752/75133268-123ae200-5715-11ea-9471-b543ff19ca99.png">

<img width="957" alt="圖片" src="https://user-images.githubusercontent.com/19990752/75133291-28e13900-5715-11ea-80d6-ab21d80912f3.png">

所以這邊就關閉您的 Issues 囉

**Comment by dogwantfly** [comment]
有了！部落格網址加了 /  ，第一篇文章從手機版網頁複製網址，就出現了，感謝～
