### ISSUE TITLE
API 中的 blogUrl 當 primary key 

### ISSUE THREAD

**Issue by shawnlin0201** [hexschool/w3hexschool-API#6]
# 以下為 ISSUES 預設模板，請勿隨意刪減刪除

> 回報問題之前請先檢查以下流程，基本上可以解決七八成的問題，建議可以切換至 Preview 觀看。

- 「部落格網址」欄位有完整填入
  - 錯誤範例：[hsiangfeng.github.io](hsiangfeng.github.io)
  - 錯誤範例：[https://hsiangfeng.github.io](hsiangfeng.github.io)
  - 正確格式：[https://hsiangfeng.github.io](https://hsiangfeng.github.io) or [https://hsiangfeng.github.io/](https://hsiangfeng.github.io/)
- 文章張貼有正確斷行
  - 錯誤範例：原生 CSS 變數運用技巧（CSS Variables）[https://w3c.hexschool.com/blog/21985acb](https://w3c.hexschool.com/blog/21985acb)
  - 正確範例：（可以參考張貼格式說明）
    - 原生 CSS 變數運用技巧（CSS Variables）
    - [https://w3c.hexschool.com/blog/21985acb](https://w3c.hexschool.com/blog/21985acb)
  - ＊注意如果你的 URL 過長，有時候表單上面會看起來疑似有斷行，但實際上並沒有斷行，所以請務必確認自己有按下斷行，你可以透過這兩個 Issues 發現都有這類問題。
    - [參賽者沒有在 API 名單內](https://github.com/hexschool/w3hexschool-API/issues/3)
    - [參賽者沒有在 API 名單內](https://github.com/hexschool/w3hexschool-API/issues/4)
- 尚未回報願不願意公開暱稱 or 還沒回報文章等。

你也可以參考看看 README 的 [API 介紹](https://github.com/hexschool/w3hexschool-API#api-%E4%BB%8B%E7%B4%B9)。

如果以上你都已經嘗試排除過了，那麼就請將下方選項框改勾選。

- [x] 以上排除問題方式我已核對。

## 請描述問題

在開發文章搜尋的相關功能上（如收藏），由於 API 沒有其他較好的 candidate Key 可供選擇，因此主要是以 blogUrl （個人部落格網址）來當作 primary key 比對，但目前遇到有人會誤開兩筆 Google 表單，導致 API 中會有重複筆數的情況，並在各個搜尋器中有不同程度的影響。

目前點到有異常的資料，不確定是否只有兩筆：
- https://ithelp.ithome.com.tw/users/20120789/articles
- https://ithelp.ithome.com.tw/users/20118686/articles

## 請提供部落格網址以及暱稱核對

[文章搜尋器](https://shawnlin0201.github.io/hexschool-2020-challenge-blog-list/)

**步驟複製（例如收藏功能）：**
- 點選收藏 (e.g. 餅乾)
- 點選已收藏排列表示，會發現 primary key 會有多筆情況。

**期望：**
- 能排除多筆 blogUrl 的情況或是提供其他資料以作為 candidate key 選擇。

感謝興趣使然的工程師們！

## Assignees

> 當你填寫完畢後請點一下旁邊 Assignees 標註 hsiangfeng (Ray)，當我看到後我就會盡快給與協助。

我這邊 Assignees 無法下拉選人，因此改用 tag 方式。

@hsiangfeng

**Comment by hsiangfeng** [comment]
Hi，shawnlin0201：

關於這個問題我在思考看看怎麼處理...

因為原本的唯一 key，其實就是 Email，但是因為個資法的關係所以不能公開，所以該 issues 我先不關閉，我在看看怎麼處理

**Comment by hsiangfeng** [comment]
Hi，shawnlin0201：
目前已經新增一個 `keyID` 可充當 primary keyID，所以可以再試試看唷

該 issue 就關閉了

**Comment by shawnlin0201** [comment]
已將 keyID 作為前端 Identity ID，相關功能已修改完成，相信其他作品同步欄位後應該都能順利開發！
[文章搜尋器](https://shawnlin0201.github.io/hexschool-2020-challenge-blog-list/)

Very thankful！

**Comment by gonsakon** [comment]
@shawnlin0201 謝謝你的開發，這裡也分享到社團上哩 :D
https://www.facebook.com/groups/110635703123103/permalink/620378938815441/

**Comment by hsiangfeng** [comment]
@shawnlin0201 這邊我也將您的作品放置進 [SEARCH.md](https://github.com/hexschool/w3hexschool-API/blob/master/SEARCH.md) 中囉~

感謝您的開發 :D
